### ISSUE TITLE
Could you please share the dataset with me? I noticed that there need a permission. Many thanks!

### ISSUE THREAD

**Issue by ZihaoZheng98** [FuZe4ever/MSG-Multimodal-Scene-Graph-Generation-in-Social-Media-Posts#1]

**Comment by FuZe4ever** [comment]
Sure! We are sorry that the authority was incorrect before. We've edited the authority so that you can download the dataset for free. Please check it. ^-^

**Comment by ZihaoZheng98** [comment]
> Sure! We are sorry that the authority was incorrect before. We've edited the authority so that you can download the dataset for free. Please check it. ^-^

Thanks! Wish you have a good day.
